#pragma once
#include <string_view>
#include <utility>

// Presentation labels never modify policy identifiers or server-provided titles.
// Static string views keep rendering allocation-free.
inline std::string_view materialLabel(std::string_view value) {
    static constexpr std::pair<std::string_view, std::string_view> labels[]{
        {"MAX STREAMING BITRATE", "Max streaming bitrate"},
        {"PLAYBACK BUFFER", "Playback buffer"},
        {"SKIP BACK", "Skip back"},
        {"SKIP AHEAD", "Skip ahead"},
        {"DEFAULT VIDEO ZOOM", "Default video zoom"},
        {"AUTOPLAY NEXT EPISODE", "Autoplay next episode"},
        {"STILL WATCHING AFTER", "Still watching after"},
        {"MATCH VIDEO REFRESH RATE", "Match video refresh rate"},
        {"WATCHED INDICATORS", "Watched indicators"},
        {"CLOCK", "Clock"},
        {"BACKDROPS", "Backdrops"},
        {"SUBTITLE SIZE", "Subtitle size"},
        {"SUBTITLE BACKGROUND", "Subtitle background"},
        {"SUBTITLE POSITION", "Subtitle position"},
        {"AUDIO OUTPUT", "Audio output"},
        {"AVC / H.264 MAX LEVEL", "AVC / H.264 max level"},
        {"HEVC / H.265 MAX LEVEL", "HEVC / H.265 max level"},
        {"HDR PLAYBACK", "HDR playback"},
        {"UI TEXT SIZE", "UI text size"},
        {"OVERSCAN SAFE AREA", "Overscan safe area"},
        {"IN-APP SCREENSAVER", "In-app screensaver"},
        {"EXTERNAL PLAYER", "External player"},
        {"DIAGNOSTICS", "Diagnostics"},
        {"SWITCH USER", "Switch user"},
        {"SUBTITLE LANGUAGES", "Subtitle languages"},
        {"TIME FORMAT", "Time format"},
        {"AUTO SUBTITLES", "Auto subtitles"},
        {"AUTO SUBTITLE LANGUAGE", "Auto subtitle language"},
        {"AUTO SUBTITLE SOURCE AUDIO", "Auto subtitle source audio"},
        {"ADVANCED SETTINGS", "Advanced settings"},
        {"KEEP WATCHING", "Keep watching"},
        {"PLAY NEXT", "Play next"},
        {"RESUME", "Resume"},
        {"PLAY", "Play"},
        {"EPISODES", "Episodes"},
        {"UNFAVORITE", "Unfavorite"},
        {"FAVORITE", "Favorite"},
        {"MARK UNWATCHED", "Mark unwatched"},
        {"MARK WATCHED", "Mark watched"},
        {"CAST", "Cast"},
        {"MORE", "More"},
        {"BACK", "Back"},
        {"PLAY ALL", "Play all"},
        {"PLAY EXTERNAL", "Play external"},
        {"VIEW QUEUE", "View queue"},
        {"SHOW ON HOME", "Show on home"},
        {"HIDE FROM HOME", "Hide from home"},
        {"REFRESH METADATA", "Refresh metadata"},
        {"DELETE MEDIA", "Delete media"},
        {"ALL", "All"},
        {"FAVORITES", "Favorites"},
        {"GENRES", "Genres"},
        {"COLLECTIONS", "Collections"},
        {"DONE", "Done"},
        {"SPACE", "Space"},
        {"DELETE", "Delete"},
        {"NORMAL", "Normal"},
        {"SMALL", "Small"},
        {"MEDIUM", "Medium"},
        {"LARGE", "Large"},
        {"EXTRA LARGE", "Extra large"},
        {"FIT", "Fit"},
        {"FILL", "Fill"},
        {"STRETCH", "Stretch"},
        {"MIDDLE", "Middle"},
        {"CLEAR", "Clear"},
        {"24 HOUR", "24 hour"},
        {"12 HOUR (AM/PM)", "12 hour (AM/PM)"},
        {"SDR ONLY", "SDR only"},
        {"ALLOW ALL HDR", "Allow all HDR"},
        {"DOWNMIX TO STEREO", "Downmix to stereo"},
        {"DEVICE / SERVER / PLAYBACK", "Device / server / playback"},
        {"CURRENT USER", "Current user"},
        {"SHOW COMMON", "Show common"},
        {"SHOW TECHNICAL", "Show technical"},
        {"ON", "On"},
        {"OFF", "Off"},
        {"AUTO", "Auto"},
        {"DEFAULT", "Default"},
        {"LOADING", "Loading"},
        {"DIMMED", "Dimmed"},
        {"LOW", "Low"},
        {"HIGH", "High"},
        {"INTERNAL", "Internal"},
        {"ALL LANGUAGES", "All languages"},
        {"ENGLISH", "English"},
        {"MAORI", "Maori"},
        {"JAPANESE", "Japanese"},
        {"SPANISH", "Spanish"},
        {"FRENCH", "French"},
        {"GERMAN", "German"},
        {"ITALIAN", "Italian"},
        {"PORTUGUESE", "Portuguese"},
        {"KOREAN", "Korean"},
        {"CHINESE", "Chinese"},
        {"ARABIC", "Arabic"},
        {"DUTCH", "Dutch"},
        {"RUSSIAN", "Russian"},
        {"HINDI", "Hindi"},
        {"SWEDISH", "Swedish"},
        {"NORWEGIAN", "Norwegian"},
    };
    for (const auto& [key, label] : labels) if (key == value) return label;
    return value;
}
